[package]
name = "aoc"
version = "0.1.0"
authors = ["Brent M. Spell <bspell1@gmail.com>"]
edition = "2021"

[dependencies]
anyhow = "1.0"
cached = "0.22"
itertools = "0.12"
lazy_static = "1.4"
num = "0.4"
rand = "0.8"
regex = "1"
