repos:
    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v3.3.0
      hooks:
          - id: check-ast
          - id: end-of-file-fixer
          - id: trailing-whitespace
          - id: check-merge-conflict
    - repo: https://github.com/psf/black
      rev: 20.8b1
      hooks:
          - id: black
    - repo: https://gitlab.com/pycqa/flake8
      rev: 3.8.4
      hooks:
          - id: flake8
            additional_dependencies:
                - flake8-black
            args: [--config=2017/.flake8]
    - repo: local
      hooks:
          - id: pylint
            name: pylint
            entry: pylint
            language: system
            exclude: ^2017/tests/
            types: [python]
            args: [--rcfile=2017/.pylintrc]
    - repo: https://github.com/timothycrosley/isort
      rev: 5.6.4
      hooks:
          - id: isort
    - repo: https://github.com/pre-commit/mirrors-mypy
      rev: v0.790
      hooks:
          - id: mypy
    - repo: local
      hooks:
          - id: pytest
            name: pytest
            language: system
            entry: bash -c 'cd 2017 && python -m pytest'
            pass_filenames: false
            always_run: true
